name: Capture TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (UTC)
  workflow_dispatch:     # Allow manual triggering from the GitHub UI

jobs:
  capture:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main          # Checkout main to access the script

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set the desired Python version

    - name: Install dependencies
      run: |
        pip install playwright        # Install Playwright for Python
        playwright install chromium   # Install Chromium browser

    - name: Capture badge screenshot
      run: python capture_badge.py   # Run the script to capture the badge

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Create an orphan branch with no history
        git checkout --orphan badges-temp
        git reset

        # Add only the image file
        git add badges/tryhackme_badge.png
        
        COMMIT_MSG="Update TryHackMe badge image - $(date -u '+%Y-%m-%d %H:%M UTC')"
        git commit -m "$COMMIT_MSG" || echo "No changes"
        git push --force origin HEAD:badges
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
